name: Release

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check changed stories
        id: stories
        run: |
          echo "changed=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q -e '^\.storybook/' -e '^stories/' && echo true || echo false)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Build Storybook
        if: steps.stories.outputs.changed == 'true' || steps.changesets.outputs.published == 'true'
        run: pnpm build-storybook

      - name: Update Storybook
        if: steps.stories.outputs.changed == 'true' || steps.changesets.outputs.published == 'true'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: storybook-static
          clean: true
          clean-exclude: .nojekyll
